<?php

function xmldb_block_reporting_upgrade($oldversion) {
    global $DB;
    $dbman = $DB->get_manager();

    /// Add a new column newcol to the mdl_myqtype_options
    if ($oldversion < 2019032510) {
        // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.
        if ($oldversion < 2019032510) {

            // Define field flag to be added to block_reporting.
            $table = new xmldb_table('block_reporting');
            $field = new xmldb_field('flag', XMLDB_TYPE_INTEGER, '1', null, XMLDB_NOTNULL, null, '0', 'created');
    
            // Conditionally launch add field flag.
            if (!$dbman->field_exists($table, $field)) {
                $dbman->add_field($table, $field);
            }
    
            // Reporting savepoint reached.
            upgrade_block_savepoint(true, 2019032510, 'reporting');
        }
    }

    return true;
}